// src/lib/stockUniverse.ts
// The bundled ("keyless") stock universe + the pure search matcher used by
// /api/stocks/search. This is intentionally separate from src/lib/tickers.ts,
// which stays a curated 30-symbol "featured" subset with mock prices for the
// existing dashboard cards. This file is the SOURCE OF TRUTH for "can I find
// this stock at all", not "what does it cost" (quotes stay in marketData.ts).
//
// TASI roster: real Tadawul main-market symbol/name pairs. Accuracy over
// quantity — every numeric code below was confirmed against a live quote
// provider (Yahoo Finance chart API, exchangeName === 'SAU') before being
// added; entries we could not verify were left out rather than guessed.
// Arabic names (arName) are only populated where we have a confident,
// correctly-spelled official Arabic name; otherwise left as ''.
export interface StockUniverseEntry {
  symbol: string;
  name: string;
  arName: string;
  market: 'TASI' | 'NASDAQ';
}

export const TASI_UNIVERSE: StockUniverseEntry[] = [
  { symbol: '1010.SR', name: 'Riyad Bank', arName: 'بنك الرياض', market: 'TASI' },
  { symbol: '1020.SR', name: 'Bank Aljazira', arName: 'بنك الجزيرة', market: 'TASI' },
  { symbol: '1030.SR', name: 'The Saudi Investment Bank', arName: 'البنك السعودي للاستثمار', market: 'TASI' },
  { symbol: '1050.SR', name: 'Banque Saudi Fransi', arName: 'البنك السعودي الفرنسي', market: 'TASI' },
  { symbol: '1060.SR', name: 'Saudi Awwal Bank', arName: 'البنك السعودي الأول', market: 'TASI' },
  { symbol: '1080.SR', name: 'Arab National Bank', arName: 'البنك العربي الوطني', market: 'TASI' },
  { symbol: '1120.SR', name: 'Al Rajhi Banking and Investment Corporation', arName: 'مصرف الراجحي', market: 'TASI' },
  { symbol: '1140.SR', name: 'Bank Albilad', arName: 'مصرف البلاد', market: 'TASI' },
  { symbol: '1150.SR', name: 'Alinma Bank', arName: 'مصرف الإنماء', market: 'TASI' },
  { symbol: '1180.SR', name: 'The Saudi National Bank', arName: 'البنك الأهلي السعودي', market: 'TASI' },
  { symbol: '2222.SR', name: 'Saudi Aramco', arName: 'أرامكو السعودية', market: 'TASI' },
  { symbol: '1211.SR', name: 'Saudi Arabian Mining Company (Maaden)', arName: 'معادن', market: 'TASI' },
  { symbol: '1201.SR', name: 'Takween Advanced Industries', arName: '', market: 'TASI' },
  { symbol: '1202.SR', name: 'Middle East Company for Manufacturing and Producing Paper', arName: '', market: 'TASI' },
  { symbol: '1301.SR', name: 'United Wire Factories Company', arName: '', market: 'TASI' },
  { symbol: '1302.SR', name: 'Bawan Company', arName: '', market: 'TASI' },
  { symbol: '1810.SR', name: 'Seera Holding Group', arName: '', market: 'TASI' },
  { symbol: '1830.SR', name: 'Leejam Sports Company', arName: '', market: 'TASI' },
  { symbol: '1832.SR', name: 'Sadr Logistics Company', arName: '', market: 'TASI' },
  { symbol: '2001.SR', name: 'Methanol Chemicals Company', arName: '', market: 'TASI' },
  { symbol: '2020.SR', name: 'SABIC Agri-Nutrients Company', arName: '', market: 'TASI' },
  { symbol: '2030.SR', name: 'Saudi Arabian Refineries Company', arName: '', market: 'TASI' },
  { symbol: '2040.SR', name: 'Saudi Ceramic Company', arName: '', market: 'TASI' },
  { symbol: '2050.SR', name: 'Savola Group Company', arName: 'مجموعة صافولا', market: 'TASI' },
  { symbol: '2060.SR', name: 'National Industrialization Company', arName: '', market: 'TASI' },
  { symbol: '2070.SR', name: 'Saudi Pharmaceutical Industries and Medical Appliances Corporation', arName: '', market: 'TASI' },
  { symbol: '2080.SR', name: 'National Gas and Industrialization Company', arName: '', market: 'TASI' },
  { symbol: '2090.SR', name: 'National Gypsum Company', arName: '', market: 'TASI' },
  { symbol: '2100.SR', name: 'Wafrah for Industry and Development Company', arName: '', market: 'TASI' },
  { symbol: '2110.SR', name: 'Saudi Cable Company', arName: '', market: 'TASI' },
  { symbol: '2120.SR', name: 'Saudi Advanced Industries Company', arName: '', market: 'TASI' },
  { symbol: '2130.SR', name: 'Saudi Industrial Development Co.', arName: '', market: 'TASI' },
  { symbol: '2140.SR', name: 'Ayyan Investment Company', arName: '', market: 'TASI' },
  { symbol: '2150.SR', name: 'The National Company for Glass Industries', arName: '', market: 'TASI' },
  { symbol: '2160.SR', name: 'The Saudi Arabian Amiantit Company', arName: '', market: 'TASI' },
  { symbol: '2170.SR', name: 'Alujain Corporation', arName: '', market: 'TASI' },
  { symbol: '2180.SR', name: 'Filling and Packing Materials Manufacturing Company', arName: '', market: 'TASI' },
  { symbol: '2190.SR', name: 'Sustained Infrastructure Holding Company', arName: '', market: 'TASI' },
  { symbol: '2200.SR', name: 'Arabian Pipes Company', arName: '', market: 'TASI' },
  { symbol: '2210.SR', name: 'Nama Chemicals Company', arName: '', market: 'TASI' },
  { symbol: '2220.SR', name: 'National Metal Manufacturing and Casting Co.', arName: '', market: 'TASI' },
  { symbol: '2230.SR', name: 'Saudi Chemical Holding Company', arName: '', market: 'TASI' },
  { symbol: '2240.SR', name: 'Advanced Building Industries Co.', arName: '', market: 'TASI' },
  { symbol: '2250.SR', name: 'Saudi Industrial Investment Group', arName: '', market: 'TASI' },
  { symbol: '2270.SR', name: 'Saudia Dairy & Foodstuff Company', arName: '', market: 'TASI' },
  { symbol: '2290.SR', name: 'Yanbu National Petrochemical Company', arName: 'ينبع الوطنية للبتروكيماويات', market: 'TASI' },
  { symbol: '2300.SR', name: 'Saudi Paper Manufacturing Company', arName: '', market: 'TASI' },
  { symbol: '2310.SR', name: 'Sahara International Petrochemical Company', arName: '', market: 'TASI' },
  { symbol: '2320.SR', name: 'Al-Babtain Power and Telecommunications Company', arName: '', market: 'TASI' },
  { symbol: '2330.SR', name: 'Advanced Petrochemical Company', arName: '', market: 'TASI' },
  { symbol: '2340.SR', name: 'Artex Industrial Investment Company', arName: '', market: 'TASI' },
  { symbol: '2350.SR', name: 'Saudi Kayan Petrochemical Company', arName: 'صدارة كيان السعودية', market: 'TASI' },
  { symbol: '2360.SR', name: 'Saudi Vitrified Clay Pipe Company', arName: '', market: 'TASI' },
  { symbol: '2370.SR', name: 'Middle East Specialized Cables Company', arName: '', market: 'TASI' },
  { symbol: '2380.SR', name: 'Rabigh Refining and Petrochemical Company', arName: 'بترو رابغ', market: 'TASI' },
  { symbol: '3002.SR', name: 'Najran Cement Company', arName: '', market: 'TASI' },
  { symbol: '3003.SR', name: 'City Cement Company', arName: '', market: 'TASI' },
  { symbol: '3004.SR', name: 'Northern Region Cement Company', arName: '', market: 'TASI' },
  { symbol: '3005.SR', name: 'Umm Al-Qura Cement Company', arName: '', market: 'TASI' },
  { symbol: '3007.SR', name: 'Zahrat Al Waha For Trading Company', arName: '', market: 'TASI' },
  { symbol: '3008.SR', name: 'Al Kathiri Holding Company', arName: '', market: 'TASI' },
  { symbol: '3010.SR', name: 'Arabian Cement Company', arName: '', market: 'TASI' },
  { symbol: '3020.SR', name: 'YAMAMA Cement Company', arName: '', market: 'TASI' },
  { symbol: '3030.SR', name: 'Saudi Cement Company', arName: '', market: 'TASI' },
  { symbol: '3040.SR', name: 'Qassim Cement Company', arName: '', market: 'TASI' },
  { symbol: '3050.SR', name: 'Southern Province Cement Company', arName: '', market: 'TASI' },
  { symbol: '3060.SR', name: 'Yanbu Cement Company', arName: '', market: 'TASI' },
  { symbol: '3080.SR', name: 'Eastern Province Cement Company', arName: '', market: 'TASI' },
  { symbol: '3090.SR', name: 'Tabuk Cement Company', arName: '', market: 'TASI' },
  { symbol: '3091.SR', name: 'Al Jouf Cement Company', arName: '', market: 'TASI' },
  { symbol: '4001.SR', name: 'Abdullah Al-Othaim Markets Company', arName: 'أسواق عبدالله العثيم', market: 'TASI' },
  { symbol: '4002.SR', name: 'Mouwasat Medical Services Company', arName: '', market: 'TASI' },
  { symbol: '4003.SR', name: 'United Electronics Company', arName: 'إكسترا', market: 'TASI' },
  { symbol: '4004.SR', name: 'Dallah Healthcare Company', arName: '', market: 'TASI' },
  { symbol: '4005.SR', name: 'National Medical Care Company', arName: '', market: 'TASI' },
  { symbol: '4006.SR', name: 'Saudi Marketing Company', arName: '', market: 'TASI' },
  { symbol: '4007.SR', name: 'Al Hammadi Holding Company', arName: '', market: 'TASI' },
  { symbol: '4008.SR', name: 'Saudi Company for Hardware SACO', arName: '', market: 'TASI' },
  { symbol: '4009.SR', name: 'Middle East Healthcare Company', arName: '', market: 'TASI' },
  { symbol: '4013.SR', name: 'Dr. Sulaiman Al Habib Medical Services Group Company', arName: '', market: 'TASI' },
  { symbol: '4014.SR', name: 'Scientific and Medical Equipment House Company', arName: '', market: 'TASI' },
  { symbol: '4015.SR', name: 'Jamjoom Pharmaceuticals Factory Company', arName: '', market: 'TASI' },
  { symbol: '4016.SR', name: 'Middle East Pharmaceutical Industries Company', arName: '', market: 'TASI' },
  { symbol: '4020.SR', name: 'Saudi Real Estate Company', arName: '', market: 'TASI' },
  { symbol: '4030.SR', name: 'The National Shipping Company of Saudi Arabia', arName: 'البحري', market: 'TASI' },
  { symbol: '4031.SR', name: 'Saudi Ground Services Company', arName: '', market: 'TASI' },
  { symbol: '4040.SR', name: 'Saudi Public Transport Company', arName: '', market: 'TASI' },
  { symbol: '4050.SR', name: 'Saudi Automotive Services Company', arName: '', market: 'TASI' },
  { symbol: '4061.SR', name: 'Anaam International Holding Group Company', arName: '', market: 'TASI' },
  { symbol: '4070.SR', name: 'Tihama for Advertising, Public Relations and Marketing Company', arName: '', market: 'TASI' },
  { symbol: '4080.SR', name: 'Sinad Holding Company', arName: '', market: 'TASI' },
  { symbol: '4090.SR', name: 'Taiba Investment Company', arName: '', market: 'TASI' },
  { symbol: '4100.SR', name: 'Makkah Construction and Development Company', arName: '', market: 'TASI' },
  { symbol: '4110.SR', name: 'Batic Investments and Logistics Company', arName: '', market: 'TASI' },
  { symbol: '4130.SR', name: 'Darb Saudi Investment Company', arName: '', market: 'TASI' },
  { symbol: '4140.SR', name: 'Saudi Industrial Export Company', arName: '', market: 'TASI' },
  { symbol: '4150.SR', name: 'Arriyadh Development Co.', arName: '', market: 'TASI' },
  { symbol: '4160.SR', name: 'Thimar Development Holding Company', arName: '', market: 'TASI' },
  { symbol: '4161.SR', name: 'BinDawood Holding Company', arName: '', market: 'TASI' },
  { symbol: '4162.SR', name: 'Almunajem Foods Company', arName: '', market: 'TASI' },
  { symbol: '4163.SR', name: 'Al-Dawaa Medical Services Company', arName: '', market: 'TASI' },
  { symbol: '4164.SR', name: 'Nahdi Medical Company', arName: '', market: 'TASI' },
  { symbol: '4170.SR', name: 'Tourism Enterprise Company (Shams)', arName: '', market: 'TASI' },
  { symbol: '4180.SR', name: 'Fitaihi Holding Group', arName: '', market: 'TASI' },
  { symbol: '4190.SR', name: 'Jarir Marketing Company', arName: 'جرير', market: 'TASI' },
  { symbol: '4191.SR', name: 'Abdullah Saad Mohammed Abo Moati for Bookstores Company', arName: '', market: 'TASI' },
  { symbol: '4200.SR', name: 'Aldrees Petroleum and Transport Services Company', arName: '', market: 'TASI' },
  { symbol: '4210.SR', name: 'Saudi Research and Media Group', arName: '', market: 'TASI' },
  { symbol: '4220.SR', name: 'Emaar The Economic City', arName: '', market: 'TASI' },
  { symbol: '4230.SR', name: 'Red Sea International Company', arName: '', market: 'TASI' },
  { symbol: '4240.SR', name: 'AFG International Company', arName: '', market: 'TASI' },
  { symbol: '4250.SR', name: 'Jabal Omar Development Company', arName: '', market: 'TASI' },
  { symbol: '4260.SR', name: 'United International Transportation Company', arName: '', market: 'TASI' },
  { symbol: '4261.SR', name: 'Theeb Rent A Car Company', arName: '', market: 'TASI' },
  { symbol: '4270.SR', name: 'Saudi Printing and Packaging Co.', arName: '', market: 'TASI' },
  { symbol: '4280.SR', name: 'Kingdom Holding Company', arName: '', market: 'TASI' },
  { symbol: '4290.SR', name: 'Al Khaleej Training and Education Company', arName: '', market: 'TASI' },
  { symbol: '4300.SR', name: 'Dar Al Arkan Real Estate Development Company', arName: 'دار الأركان', market: 'TASI' },
  { symbol: '4310.SR', name: 'Knowledge Economic City Company', arName: '', market: 'TASI' },
  { symbol: '4320.SR', name: 'Alandalus Property Company', arName: '', market: 'TASI' },
  { symbol: '6001.SR', name: 'Halwani Bros. Co. Ltd.', arName: '', market: 'TASI' },
  { symbol: '6002.SR', name: 'Herfy Food Services Company', arName: '', market: 'TASI' },
  { symbol: '6004.SR', name: 'CATRION Catering Holding Company', arName: '', market: 'TASI' },
  { symbol: '6010.SR', name: 'The National Agricultural Development Company', arName: '', market: 'TASI' },
  { symbol: '6012.SR', name: 'Raydan Food Company', arName: '', market: 'TASI' },
  { symbol: '6013.SR', name: 'Development Works Food Company', arName: '', market: 'TASI' },
  { symbol: '6014.SR', name: 'Alamar Foods Company', arName: '', market: 'TASI' },
  { symbol: '6015.SR', name: 'Americana Restaurants International PLC', arName: '', market: 'TASI' },
  { symbol: '6016.SR', name: 'Shatirah House Restaurant Co.', arName: '', market: 'TASI' },
  { symbol: '6017.SR', name: 'Jahez International Company for Information Systems Technology', arName: '', market: 'TASI' },
  { symbol: '6018.SR', name: 'Sport Clubs Company', arName: '', market: 'TASI' },
  { symbol: '6020.SR', name: 'Al Gassim Investment Holding Company', arName: '', market: 'TASI' },
  { symbol: '6040.SR', name: 'Tabuk Agricultural Development Company', arName: '', market: 'TASI' },
  { symbol: '6050.SR', name: 'Saudi Fisheries Company', arName: '', market: 'TASI' },
  { symbol: '6060.SR', name: 'Ash-Sharqiyah Development Co.', arName: 'الشرقية للتنمية', market: 'TASI' },
  { symbol: '6070.SR', name: 'Al-Jouf Agricultural Development Co.', arName: '', market: 'TASI' },
  { symbol: '6090.SR', name: 'Jazan Development and Investment Company', arName: '', market: 'TASI' },
  { symbol: '7010.SR', name: 'Saudi Telecom Company', arName: 'اس تي سي', market: 'TASI' },
  { symbol: '7020.SR', name: 'Etihad Etisalat Company', arName: 'موبايلي', market: 'TASI' },
  { symbol: '7030.SR', name: 'Mobile Telecommunications Company Saudi Arabia', arName: '', market: 'TASI' },
  { symbol: '7040.SR', name: 'Etihad GO Telecom Co.', arName: '', market: 'TASI' },
  { symbol: '7200.SR', name: 'Al Moammar Information Systems Company', arName: '', market: 'TASI' },
  { symbol: '7201.SR', name: 'Arab Sea Information Systems Company', arName: '', market: 'TASI' },
  { symbol: '7202.SR', name: 'Arabian Internet and Communication Services Company', arName: '', market: 'TASI' },
  { symbol: '7203.SR', name: 'Elm Company', arName: '', market: 'TASI' },
  { symbol: '7204.SR', name: 'Perfect Presentation for Commercial Services Company', arName: '', market: 'TASI' },
  { symbol: '8010.SR', name: 'The Company for Cooperative Insurance', arName: '', market: 'TASI' },
  { symbol: '8012.SR', name: 'Aljazira Takaful Taawuni Company', arName: '', market: 'TASI' },
  { symbol: '8020.SR', name: 'Malath Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8030.SR', name: 'The Mediterranean and Gulf Cooperative Insurance and Reinsurance Company', arName: '', market: 'TASI' },
  { symbol: '8040.SR', name: 'Mutakamela Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8050.SR', name: 'Salama Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8060.SR', name: 'Walaa Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8070.SR', name: 'Arabian Shield Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8100.SR', name: 'Saudi Arabian Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8120.SR', name: 'Gulf Union Alahlia Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8150.SR', name: 'Allied Cooperative Insurance Group', arName: '', market: 'TASI' },
  { symbol: '8160.SR', name: 'Arabia Insurance Cooperative Company', arName: '', market: 'TASI' },
  { symbol: '8170.SR', name: 'Al-Etihad Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8180.SR', name: 'Al Sagr Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8190.SR', name: 'United Cooperative Assurance Company', arName: '', market: 'TASI' },
  { symbol: '8200.SR', name: 'Saudi Reinsurance Company', arName: '', market: 'TASI' },
  { symbol: '8210.SR', name: 'Bupa Arabia for Cooperative Insurance Company', arName: 'بوبا العربية', market: 'TASI' },
  { symbol: '8230.SR', name: 'Al Rajhi Company for Cooperative Insurance', arName: '', market: 'TASI' },
  { symbol: '8240.SR', name: 'Chubb Arabia Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8250.SR', name: 'Gulf Insurance Group', arName: 'مجموعة الخليج للتأمين', market: 'TASI' },
  { symbol: '8260.SR', name: 'Gulf General Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8280.SR', name: 'Liva Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8300.SR', name: 'Wataniya Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8310.SR', name: 'Amana Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '8311.SR', name: 'Saudi Enaya Cooperative Insurance Company', arName: '', market: 'TASI' },
  { symbol: '5110.SR', name: 'Saudi Electricity Company', arName: 'الكهرباء السعودية', market: 'TASI' },
];

// NASDAQ bundled fallback used when ALPACA_API_KEY is unset (keyless dev / CI).
// All real, well-known Nasdaq-listed tickers.
export const NASDAQ_UNIVERSE_FALLBACK: StockUniverseEntry[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', arName: 'أبل', market: 'NASDAQ' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', arName: 'إنفيديا', market: 'NASDAQ' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', arName: 'مايكروسوفت', market: 'NASDAQ' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', arName: 'ألفابت (جوجل)', market: 'NASDAQ' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', arName: 'أمازون', market: 'NASDAQ' },
  { symbol: 'META', name: 'Meta Platforms Inc.', arName: 'ميتا', market: 'NASDAQ' },
  { symbol: 'TSLA', name: 'Tesla Motors', arName: 'تسلا', market: 'NASDAQ' },
  { symbol: 'NFLX', name: 'Netflix Inc.', arName: 'نتفلكس', market: 'NASDAQ' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', arName: 'إيه إم دي', market: 'NASDAQ' },
  { symbol: 'INTC', name: 'Intel Corp.', arName: 'إنتل', market: 'NASDAQ' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', arName: 'كوالكوم', market: 'NASDAQ' },
  { symbol: 'COST', name: 'Costco Wholesale', arName: 'كوستكو', market: 'NASDAQ' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', arName: 'بيبسي', market: 'NASDAQ' },
  { symbol: 'SBUX', name: 'Starbucks Corp.', arName: 'ستاربكس', market: 'NASDAQ' },
  { symbol: 'ADBE', name: 'Adobe Inc.', arName: 'أدوبي', market: 'NASDAQ' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', arName: '', market: 'NASDAQ' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'INTU', name: 'Intuit Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'AMGN', name: 'Amgen Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', arName: '', market: 'NASDAQ' },
  { symbol: 'KLAC', name: 'KLA Corporation', arName: '', market: 'NASDAQ' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'MU', name: 'Micron Technology Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'MRNA', name: 'Moderna Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'EA', name: 'Electronic Arts Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'MAR', name: 'Marriott International Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc.", arName: '', market: 'NASDAQ' },
  { symbol: 'CTAS', name: 'Cintas Corporation', arName: '', market: 'NASDAQ' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'PAYX', name: 'Paychex Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'CSX', name: 'CSX Corporation', arName: '', market: 'NASDAQ' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', arName: '', market: 'NASDAQ' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', arName: '', market: 'NASDAQ' },
  { symbol: 'DXCM', name: 'DexCom Inc.', arName: '', market: 'NASDAQ' },
];

/**
 * Pure symbol/name (English or Arabic) substring matcher. No network, no
 * Prisma — kept side-effect free so it is unit-testable without mocking.
 */
export function searchUniverse(
  universe: StockUniverseEntry[],
  query: string,
  limit = 30
): StockUniverseEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const matches: StockUniverseEntry[] = [];
  for (const entry of universe) {
    if (
      entry.symbol.toLowerCase().includes(q) ||
      entry.name.toLowerCase().includes(q) ||
      entry.arName.toLowerCase().includes(q)
    ) {
      matches.push(entry);
      if (matches.length >= limit) break;
    }
  }
  return matches;
}
