// src/services/engines.ts

import { prisma } from '@/lib/prisma';
import { Prisma } from '@prisma/client';

/**
 * Gamification Engine: Add XP and calculate level ups
 */
export async function addXP(userId: string, amount: number) {
  let profile = await prisma.gamificationProfile.findUnique({
    where: { userId }
  });

  if (!profile) {
    profile = await prisma.gamificationProfile.create({
      data: { userId, xp: 0, level: 1 }
    });
  }

  const newXp = profile.xp + amount;
  // Level = floor(sqrt(totalXp / 100)) + 1
  const newLevel = Math.floor(Math.sqrt(newXp / 100)) + 1;

  await prisma.gamificationProfile.update({
    where: { userId },
    data: {
      xp: newXp,
      level: newLevel
    }
  });

  return { xp: newXp, level: newLevel, leveledUp: newLevel > profile.level };
}

/**
 * Sweep Logic Engine: Calculate platform Mudarib share and user profit share for Savings Jars (Mudarabah distribution)
 */
export async function processCashSweeps(customYieldRate?: Prisma.Decimal) {
  const jars = await prisma.savingsJar.findMany();
  
  // Simulated underlying pool daily yield (variable, non-guaranteed)
  // If customYieldRate is provided (for testing), use it;
  // otherwise generate a random annualized yield between 1.5% and 4.5% divided by 365.
  const poolDailyYield = customYieldRate ?? 
    new Prisma.Decimal((0.015 + Math.random() * 0.03).toFixed(6)).div(365);

  let totalPlatformRevenue = new Prisma.Decimal(0);

  for (const jar of jars) {
    const balance = new Prisma.Decimal(jar.balance.toString());
    if (balance.gt(0)) {
      // Calculate total profit generated by this jar's capital
      const totalProfit = balance.mul(poolDailyYield);
      
      // User ratio based on basis points (default is 70% or 7000 bps)
      const ratioBps = jar.profitShareRatioBps ?? 7000;
      const userRatio = new Prisma.Decimal(ratioBps).div(10000);
      const platformRatio = new Prisma.Decimal(1).sub(userRatio);

      const userProfit = totalProfit.mul(userRatio);
      const platformMargin = totalProfit.mul(platformRatio);

      // Credit the user's jar with their profit share
      await prisma.savingsJar.update({
        where: { id: jar.id },
        data: {
          balance: balance.add(userProfit)
        }
      });

      // Write audit transaction log for the profit share distribution
      await prisma.transaction.create({
        data: {
          userId: jar.userId,
          amount: userProfit,
          currency: jar.currency,
          type: 'PROFIT_SHARE',
          description: `Mudarabah profit split (${(jar.profitShareRatioBps / 100).toFixed(1)}% split)`
        }
      });

      totalPlatformRevenue = totalPlatformRevenue.add(platformMargin);
    }
  }

  return {
    processedJars: jars.length,
    platformRevenue: totalPlatformRevenue.toNumber()
  };
}
