// src/components/markets/yahooFinanceData.ts

export interface YahooStockMetric {
  symbol: string;
  name: string;
  arName: string;
  sector: string;
  sectorAr: string;
  marketCap: number; // in USD
  peRatio: number | null;
  avgVolume: number; // 3-month average
  fiftyTwoWeekLow: number;
  fiftyTwoWeekHigh: number;
}

function metric(
  symbol: string,
  name: string,
  arName: string,
  sector: string,
  sectorAr: string,
  marketCap: number,
  avgVolume: number,
  fiftyTwoWeekLow: number,
  fiftyTwoWeekHigh: number,
): YahooStockMetric {
  return {
    symbol,
    name,
    arName,
    sector,
    sectorAr,
    marketCap,
    peRatio: null,
    avgVolume,
    fiftyTwoWeekLow,
    fiftyTwoWeekHigh,
  };
}

export const YAHOO_STOCK_METRICS: Record<string, YahooStockMetric> = {
  // Additional Nasdaq-100 representatives. Membership follows Nasdaq's 2026
  // constituent publications; screener fundamentals remain disclosed estimates.
  ...Object.fromEntries([
    metric('AMAT', 'Applied Materials Inc.', 'أبلايد ماتيريالز', 'Semiconductors', 'أشباه الموصلات', 130e9, 6.5e6, 145, 255),
    metric('ASML', 'ASML Holding N.V.', 'إيه إس إم إل', 'Semiconductors', 'أشباه الموصلات', 300e9, 1.4e6, 570, 1_100),
    metric('ARM', 'Arm Holdings plc', 'آرم هولدينغز', 'Semiconductors', 'أشباه الموصلات', 140e9, 8e6, 80, 180),
    metric('MRVL', 'Marvell Technology Inc.', 'مارفيل تكنولوجي', 'Semiconductors', 'أشباه الموصلات', 70e9, 12e6, 45, 127),
    metric('MCHP', 'Microchip Technology Inc.', 'مايكروتشيب تكنولوجي', 'Semiconductors', 'أشباه الموصلات', 50e9, 7e6, 50, 100),
    metric('MPWR', 'Monolithic Power Systems Inc.', 'مونوليثيك باور سيستمز', 'Semiconductors', 'أشباه الموصلات', 35e9, 800_000, 500, 950),
    metric('PLTR', 'Palantir Technologies Inc.', 'بالانتير', 'Technology', 'التقنية', 250e9, 55e6, 20, 135),
    metric('APP', 'AppLovin Corporation', 'أب لوفين', 'Technology', 'التقنية', 200e9, 5e6, 60, 525),
    metric('DDOG', 'Datadog Inc.', 'داتا دوغ', 'Technology', 'التقنية', 45e9, 4e6, 80, 170),
    metric('ADSK', 'Autodesk Inc.', 'أوتوديسك', 'Technology', 'التقنية', 50e9, 1.8e6, 195, 330),
    metric('WDAY', 'Workday Inc.', 'وورك داي', 'Technology', 'التقنية', 60e9, 2.3e6, 200, 310),
    metric('AEP', 'American Electric Power Co.', 'أمريكان إلكتريك باور', 'Utilities', 'المرافق', 65e9, 3e6, 70, 105),
    metric('CEG', 'Constellation Energy Corp.', 'كونستليشن إنرجي', 'Utilities', 'المرافق', 110e9, 3.5e6, 160, 375),
    metric('EXC', 'Exelon Corporation', 'إكسيلون', 'Utilities', 'المرافق', 50e9, 7e6, 34, 49),
    metric('XEL', 'Xcel Energy Inc.', 'إكسل إنرجي', 'Utilities', 'المرافق', 45e9, 4e6, 46, 74),
    metric('BKR', 'Baker Hughes Company', 'بيكر هيوز', 'Energy', 'الطاقة', 50e9, 7e6, 30, 50),
    metric('FANG', 'Diamondback Energy Inc.', 'دايموندباك إنرجي', 'Energy', 'الطاقة', 45e9, 2e6, 135, 215),
    metric('WMT', 'Walmart Inc.', 'وولمارت', 'Consumer Defensive', 'الاستهلاك الدفاعي', 900e9, 17e6, 65, 110),
    metric('KHC', 'The Kraft Heinz Company', 'كرافت هاينز', 'Consumer Defensive', 'الاستهلاك الدفاعي', 30e9, 8e6, 27, 38),
    metric('MNST', 'Monster Beverage Corp.', 'مونستر بيفريدج', 'Consumer Defensive', 'الاستهلاك الدفاعي', 75e9, 6e6, 43, 68),
    metric('CCEP', 'Coca-Cola Europacific Partners', 'كوكاكولا يوروباسيفيك', 'Consumer Defensive', 'الاستهلاك الدفاعي', 45e9, 1.6e6, 68, 95),
    metric('HON', 'Honeywell International Inc.', 'هانيويل', 'Industrials', 'الصناعات', 140e9, 3e6, 180, 245),
    metric('FAST', 'Fastenal Company', 'فاستنال', 'Industrials', 'الصناعات', 45e9, 4e6, 56, 85),
    metric('ODFL', 'Old Dominion Freight Line', 'أولد دومينيون فريت لاين', 'Industrials', 'الصناعات', 45e9, 1.7e6, 165, 235),
    metric('AXON', 'Axon Enterprise Inc.', 'أكسون إنتربرايز', 'Industrials', 'الصناعات', 60e9, 900_000, 270, 800),
    metric('ALNY', 'Alnylam Pharmaceuticals Inc.', 'ألنيلام فارماسوتيكالز', 'Healthcare', 'الرعاية الصحية', 70e9, 1.1e6, 140, 330),
    metric('IDXX', 'IDEXX Laboratories Inc.', 'آيديكس لابوراتوريز', 'Healthcare', 'الرعاية الصحية', 45e9, 500_000, 390, 600),
    metric('GEHC', 'GE HealthCare Technologies', 'جي إي هيلث كير', 'Healthcare', 'الرعاية الصحية', 35e9, 3e6, 62, 95),
    metric('MELI', 'MercadoLibre Inc.', 'ميركادو ليبري', 'Consumer Cyclical', 'الاستهلاك الدوري', 120e9, 500_000, 1_450, 2_600),
    metric('DASH', 'DoorDash Inc.', 'دور داش', 'Consumer Cyclical', 'الاستهلاك الدوري', 90e9, 4e6, 95, 235),
  ].map((stock) => [stock.symbol, stock])),
  AAPL: {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    arName: 'أبل',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 3020000000000,
    peRatio: 28.5,
    avgVolume: 52000000,
    fiftyTwoWeekLow: 165.0,
    fiftyTwoWeekHigh: 198.0
  },
  NVDA: {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    arName: 'إنفيديا',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 2950000000000,
    peRatio: 72.4,
    avgVolume: 40000000,
    fiftyTwoWeekLow: 110.0,
    fiftyTwoWeekHigh: 950.0
  },
  MSFT: {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    arName: 'مايكروسوفت',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 3150000000000,
    peRatio: 35.2,
    avgVolume: 24000000,
    fiftyTwoWeekLow: 330.0,
    fiftyTwoWeekHigh: 420.0
  },
  GOOGL: {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    arName: 'ألفابت (جوجل)',
    sector: 'Communication Services',
    sectorAr: 'خدمات الاتصالات',
    marketCap: 1820000000000,
    peRatio: 25.1,
    avgVolume: 28000000,
    fiftyTwoWeekLow: 120.0,
    fiftyTwoWeekHigh: 160.0
  },
  AMZN: {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    arName: 'أمازون',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 1710000000000,
    peRatio: 61.2,
    avgVolume: 38000000,
    fiftyTwoWeekLow: 115.0,
    fiftyTwoWeekHigh: 180.0
  },
  META: {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    arName: 'ميتا',
    sector: 'Communication Services',
    sectorAr: 'خدمات الاتصالات',
    marketCap: 1180000000000,
    peRatio: 31.8,
    avgVolume: 18000000,
    fiftyTwoWeekLow: 280.0,
    fiftyTwoWeekHigh: 510.0
  },
  TSLA: {
    symbol: 'TSLA',
    name: 'Tesla Motors',
    arName: 'تسلا',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 705000000000,
    peRatio: 42.6,
    avgVolume: 85000000,
    fiftyTwoWeekLow: 138.0,
    fiftyTwoWeekHigh: 299.0
  },
  NFLX: {
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    arName: 'نتفلكس',
    sector: 'Communication Services',
    sectorAr: 'خدمات الاتصالات',
    marketCap: 245000000000,
    peRatio: 45.3,
    avgVolume: 3500000,
    fiftyTwoWeekLow: 340.0,
    fiftyTwoWeekHigh: 630.0
  },
  AMD: {
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    arName: 'إيه إم دي',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 282000000000,
    peRatio: 330.0,
    avgVolume: 62000000,
    fiftyTwoWeekLow: 93.0,
    fiftyTwoWeekHigh: 227.0
  },
  INTC: {
    symbol: 'INTC',
    name: 'Intel Corp.',
    arName: 'إنتل',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 182000000000,
    peRatio: 85.0,
    avgVolume: 35000000,
    fiftyTwoWeekLow: 26.0,
    fiftyTwoWeekHigh: 50.0
  },
  QCOM: {
    symbol: 'QCOM',
    name: 'Qualcomm Inc.',
    arName: 'كوالكوم',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 178000000000,
    peRatio: 21.3,
    avgVolume: 8100000,
    fiftyTwoWeekLow: 100.0,
    fiftyTwoWeekHigh: 175.0
  },
  COST: {
    symbol: 'COST',
    name: 'Costco Wholesale',
    arName: 'كوستكو',
    sector: 'Consumer Defensive',
    sectorAr: 'الاستهلاك الدفاعي',
    marketCap: 325000000000,
    peRatio: 48.2,
    avgVolume: 2100000,
    fiftyTwoWeekLow: 470.0,
    fiftyTwoWeekHigh: 750.0
  },
  PEP: {
    symbol: 'PEP',
    name: 'PepsiCo Inc.',
    arName: 'بيبسي',
    sector: 'Consumer Defensive',
    sectorAr: 'الاستهلاك الدفاعي',
    marketCap: 232000000000,
    peRatio: 26.4,
    avgVolume: 5200000,
    fiftyTwoWeekLow: 155.0,
    fiftyTwoWeekHigh: 196.0
  },
  SBUX: {
    symbol: 'SBUX',
    name: 'Starbucks Corp.',
    arName: 'ستاربكس',
    sector: 'Consumer Defensive',
    sectorAr: 'الاستهلاك الدفاعي',
    marketCap: 104000000000,
    peRatio: 23.5,
    avgVolume: 8500000,
    fiftyTwoWeekLow: 89.0,
    fiftyTwoWeekHigh: 115.0
  },
  ADBE: {
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    arName: 'أدوبي',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 248000000000,
    peRatio: 48.0,
    avgVolume: 2900000,
    fiftyTwoWeekLow: 430.0,
    fiftyTwoWeekHigh: 638.0
  },
  CSCO: {
    symbol: 'CSCO',
    name: 'Cisco Systems Inc.',
    arName: 'سيسكو',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 198000000000,
    peRatio: 15.4,
    avgVolume: 18000000,
    fiftyTwoWeekLow: 44.0,
    fiftyTwoWeekHigh: 58.0
  },
  CMCSA: {
    symbol: 'CMCSA',
    name: 'Comcast Corporation',
    arName: 'كومكاست',
    sector: 'Communication Services',
    sectorAr: 'خدمات الاتصالات',
    marketCap: 162000000000,
    peRatio: 11.2,
    avgVolume: 19000000,
    fiftyTwoWeekLow: 36.0,
    fiftyTwoWeekHigh: 48.0
  },
  TXN: {
    symbol: 'TXN',
    name: 'Texas Instruments Inc.',
    arName: 'تكساس إنسترومنتس',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 154000000000,
    peRatio: 24.5,
    avgVolume: 6200000,
    fiftyTwoWeekLow: 140.0,
    fiftyTwoWeekHigh: 185.0
  },
  AVGO: {
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    arName: 'برودكوم',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 648000000000,
    peRatio: 68.2,
    avgVolume: 2800000,
    fiftyTwoWeekLow: 780.0,
    fiftyTwoWeekHigh: 1400.0
  },
  TMUS: {
    symbol: 'TMUS',
    name: 'T-Mobile US Inc.',
    arName: 'تي موبايل',
    sector: 'Communication Services',
    sectorAr: 'خدمات الاتصالات',
    marketCap: 192000000000,
    peRatio: 24.3,
    avgVolume: 5800000,
    fiftyTwoWeekLow: 125.0,
    fiftyTwoWeekHigh: 168.0
  },
  INTU: {
    symbol: 'INTU',
    name: 'Intuit Inc.',
    arName: 'إنتويت',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 172000000000,
    peRatio: 58.2,
    avgVolume: 1600000,
    fiftyTwoWeekLow: 390.0,
    fiftyTwoWeekHigh: 660.0
  },
  AMGN: {
    symbol: 'AMGN',
    name: 'Amgen Inc.',
    arName: 'أمجين',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 142000000000,
    peRatio: 18.2,
    avgVolume: 2600000,
    fiftyTwoWeekLow: 210.0,
    fiftyTwoWeekHigh: 320.0
  },
  ISRG: {
    symbol: 'ISRG',
    name: 'Intuitive Surgical Inc.',
    arName: 'إنتويتيف سيرجيكال',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 132000000000,
    peRatio: 78.4,
    avgVolume: 1800000,
    fiftyTwoWeekLow: 240.0,
    fiftyTwoWeekHigh: 400.0
  },
  BKNG: {
    symbol: 'BKNG',
    name: 'Booking Holdings Inc.',
    arName: 'بوكينج القابضة',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 124000000000,
    peRatio: 31.8,
    avgVolume: 400000,
    fiftyTwoWeekLow: 2400.0,
    fiftyTwoWeekHigh: 3900.0
  },
  MDLZ: {
    symbol: 'MDLZ',
    name: 'Mondelez International Inc.',
    arName: 'مونديليز الدولية',
    sector: 'Consumer Defensive',
    sectorAr: 'الاستهلاك الدفاعي',
    marketCap: 94000000000,
    peRatio: 22.1,
    avgVolume: 3800000,
    fiftyTwoWeekLow: 65.0,
    fiftyTwoWeekHigh: 78.0
  },
  GILD: {
    symbol: 'GILD',
    name: 'Gilead Sciences Inc.',
    arName: 'جلياد للعلوم',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 91000000000,
    peRatio: 16.5,
    avgVolume: 6400000,
    fiftyTwoWeekLow: 62.0,
    fiftyTwoWeekHigh: 88.0
  },
  ADP: {
    symbol: 'ADP',
    name: 'Automatic Data Processing Inc.',
    arName: 'أوتوماتيك داتا بروسيسنج',
    sector: 'Financial Services',
    sectorAr: 'الخدمات المالية',
    marketCap: 97000000000,
    peRatio: 27.4,
    avgVolume: 1800000,
    fiftyTwoWeekLow: 200.0,
    fiftyTwoWeekHigh: 260.0
  },
  VRTX: {
    symbol: 'VRTX',
    name: 'Vertex Pharmaceuticals Inc.',
    arName: 'فيرتكس فارماسوتيكالز',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 106000000000,
    peRatio: 29.3,
    avgVolume: 1300000,
    fiftyTwoWeekLow: 300.0,
    fiftyTwoWeekHigh: 448.0
  },
  REGN: {
    symbol: 'REGN',
    name: 'Regeneron Pharmaceuticals Inc.',
    arName: 'ريجينيرون',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 96000000000,
    peRatio: 28.1,
    avgVolume: 600000,
    fiftyTwoWeekLow: 680.0,
    fiftyTwoWeekHigh: 990.0
  },
  PYPL: {
    symbol: 'PYPL',
    name: 'PayPal Holdings Inc.',
    arName: 'بايبال',
    sector: 'Financial Services',
    sectorAr: 'الخدمات المالية',
    marketCap: 67000000000,
    peRatio: 15.5,
    avgVolume: 14000000,
    fiftyTwoWeekLow: 50.0,
    fiftyTwoWeekHigh: 78.0
  },
  ADI: {
    symbol: 'ADI',
    name: 'Analog Devices Inc.',
    arName: 'أنالوج ديفايسز',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 94000000000,
    peRatio: 26.2,
    avgVolume: 3200000,
    fiftyTwoWeekLow: 150.0,
    fiftyTwoWeekHigh: 200.0
  },
  LRCX: {
    symbol: 'LRCX',
    name: 'Lam Research Corporation',
    arName: 'لام ريسيرش',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 108000000000,
    peRatio: 31.2,
    avgVolume: 1200000,
    fiftyTwoWeekLow: 520.0,
    fiftyTwoWeekHigh: 980.0
  },
  KLAC: {
    symbol: 'KLAC',
    name: 'KLA Corporation',
    arName: 'كي إل إيه',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 83000000000,
    peRatio: 29.5,
    avgVolume: 1000000,
    fiftyTwoWeekLow: 410.0,
    fiftyTwoWeekHigh: 720.0
  },
  SNPS: {
    symbol: 'SNPS',
    name: 'Synopsys Inc.',
    arName: 'سينوبسيس',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 80000000000,
    peRatio: 61.5,
    avgVolume: 900000,
    fiftyTwoWeekLow: 330.0,
    fiftyTwoWeekHigh: 580.0
  },
  CDNS: {
    symbol: 'CDNS',
    name: 'Cadence Design Systems Inc.',
    arName: 'كيدنس ديزاين سيستمز',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 76000000000,
    peRatio: 75.1,
    avgVolume: 1100000,
    fiftyTwoWeekLow: 180.0,
    fiftyTwoWeekHigh: 320.0
  },
  MU: {
    symbol: 'MU',
    name: 'Micron Technology Inc.',
    arName: 'ميكرون تكنولوجي',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 118000000000,
    peRatio: null,
    avgVolume: 22000000,
    fiftyTwoWeekLow: 60.0,
    fiftyTwoWeekHigh: 130.0
  },
  PANW: {
    symbol: 'PANW',
    name: 'Palo Alto Networks Inc.',
    arName: 'بالو ألتو نيتوركس',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 93000000000,
    peRatio: 45.8,
    avgVolume: 4200000,
    fiftyTwoWeekLow: 180.0,
    fiftyTwoWeekHigh: 380.0
  },
  CRWD: {
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings Inc.',
    arName: 'كراود سترايك',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 73000000000,
    peRatio: null,
    avgVolume: 3600000,
    fiftyTwoWeekLow: 115.0,
    fiftyTwoWeekHigh: 390.0
  },
  ABNB: {
    symbol: 'ABNB',
    name: 'Airbnb Inc.',
    arName: 'إير بي إن بي',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 93000000000,
    peRatio: 38.5,
    avgVolume: 4800000,
    fiftyTwoWeekLow: 105.0,
    fiftyTwoWeekHigh: 165.0
  },
  MRNA: {
    symbol: 'MRNA',
    name: 'Moderna Inc.',
    arName: 'موديرنا',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 37000000000,
    peRatio: null,
    avgVolume: 8500000,
    fiftyTwoWeekLow: 65.0,
    fiftyTwoWeekHigh: 170.0
  },
  EA: {
    symbol: 'EA',
    name: 'Electronic Arts Inc.',
    arName: 'إلكترونيك آرتس',
    sector: 'Communication Services',
    sectorAr: 'خدمات الاتصالات',
    marketCap: 35000000000,
    peRatio: 32.4,
    avgVolume: 2100000,
    fiftyTwoWeekLow: 110.0,
    fiftyTwoWeekHigh: 145.0
  },
  MAR: {
    symbol: 'MAR',
    name: 'Marriott International Inc.',
    arName: 'ماريوت الدولية',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 66000000000,
    peRatio: 23.4,
    avgVolume: 1900000,
    fiftyTwoWeekLow: 160.0,
    fiftyTwoWeekHigh: 245.0
  },
  ORLY: {
    symbol: 'ORLY',
    name: "O'Reilly Automotive Inc.",
    arName: 'أورايلي أوتوموتيف',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 60000000000,
    peRatio: 26.2,
    avgVolume: 500000,
    fiftyTwoWeekLow: 800.0,
    fiftyTwoWeekHigh: 1100.0
  },
  CTAS: {
    symbol: 'CTAS',
    name: 'Cintas Corporation',
    arName: 'سينتاس الكبرى',
    sector: 'Industrials',
    sectorAr: 'الصناعات',
    marketCap: 60000000000,
    peRatio: 42.1,
    avgVolume: 500000,
    fiftyTwoWeekLow: 450.0,
    fiftyTwoWeekHigh: 640.0
  },
  PCAR: {
    symbol: 'PCAR',
    name: 'PACCAR Inc.',
    arName: 'باكار الكبرى',
    sector: 'Industrials',
    sectorAr: 'الصناعات',
    marketCap: 50000000000,
    peRatio: 12.8,
    avgVolume: 2400000,
    fiftyTwoWeekLow: 78.0,
    fiftyTwoWeekHigh: 125.0
  },
  PAYX: {
    symbol: 'PAYX',
    name: 'Paychex Inc.',
    arName: 'بي تشيكس',
    sector: 'Financial Services',
    sectorAr: 'الخدمات المالية',
    marketCap: 43000000000,
    peRatio: 26.1,
    avgVolume: 2200000,
    fiftyTwoWeekLow: 105.0,
    fiftyTwoWeekHigh: 132.0
  },
  ROST: {
    symbol: 'ROST',
    name: 'Ross Stores Inc.',
    arName: 'روس ستورز',
    sector: 'Consumer Cyclical',
    sectorAr: 'الاستهلاك الدوري',
    marketCap: 46000000000,
    peRatio: 25.1,
    avgVolume: 3200000,
    fiftyTwoWeekLow: 100.0,
    fiftyTwoWeekHigh: 148.0
  },
  KDP: {
    symbol: 'KDP',
    name: 'Keurig Dr Pepper Inc.',
    arName: 'كيوريج دكتور بيبر',
    sector: 'Consumer Defensive',
    sectorAr: 'الاستهلاك الدفاعي',
    marketCap: 44000000000,
    peRatio: 19.5,
    avgVolume: 7100000,
    fiftyTwoWeekLow: 28.0,
    fiftyTwoWeekHigh: 37.0
  },
  CSX: {
    symbol: 'CSX',
    name: 'CSX Corporation',
    arName: 'سي إس إكس',
    sector: 'Industrials',
    sectorAr: 'الصناعات',
    marketCap: 63000000000,
    peRatio: 18.2,
    avgVolume: 14000000,
    fiftyTwoWeekLow: 28.0,
    fiftyTwoWeekHigh: 39.0
  },
  NXPI: {
    symbol: 'NXPI',
    name: 'NXP Semiconductors N.V.',
    arName: 'إن إكس بي سيميكونداكتورز',
    sector: 'Semiconductors',
    sectorAr: 'أشباه الموصلات',
    marketCap: 56000000000,
    peRatio: 21.0,
    avgVolume: 2400000,
    fiftyTwoWeekLow: 170.0,
    fiftyTwoWeekHigh: 250.0
  },
  FTNT: {
    symbol: 'FTNT',
    name: 'Fortinet Inc.',
    arName: 'فورتينت',
    sector: 'Technology',
    sectorAr: 'التقنية',
    marketCap: 50000000000,
    peRatio: 40.5,
    avgVolume: 5800000,
    fiftyTwoWeekLow: 45.0,
    fiftyTwoWeekHigh: 80.0
  },
  DXCM: {
    symbol: 'DXCM',
    name: 'DexCom Inc.',
    arName: 'ديكسكوم الكبرى',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    marketCap: 46000000000,
    peRatio: 68.0,
    avgVolume: 3200000,
    fiftyTwoWeekLow: 80.0,
    fiftyTwoWeekHigh: 140.0
  }
};
